title = "Samuel Guyah"
theme = "archie"
paginate = 10
pygmentsstyle = "monokai"
baseURL = "/"
languageCode = "en-us"
copyright = ""

[params]
  scheme = "preference" # light, dark, gray or preference
  subtitle = "Let this be my last song."
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

[menu]
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/ChiefMateStarbuck"
    weight = -100
